# Generated by Django 4.2.10 on 2024-02-16 00:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, choices=[('C', 'Cachorro'), ('G', 'Gato')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Petshop',
                'verbose_name_plural': 'Petshops',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('nome_pet', models.CharField(max_length=50)),
                ('porte', models.IntegerField(blank=True, choices=[(0, 'Pequeno'), (1, 'Médio'), (2, 'Grande')], null=True)),
                ('data_reserva', models.DateField(blank=True, help_text='Ultilize o formato dd/mm/aaaa', null=True)),
                ('turno', models.CharField(blank=True, choices=[('manhã', 'Manhã'), ('tarde', 'Tarde')], max_length=120)),
                ('observacoes', models.TextField(blank=True, max_length=3000, verbose_name='Observações')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='reserva.categoriaanimal')),
                ('petshop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='reserva.petshop')),
            ],
            options={
                'verbose_name': 'Reserva de Banho',
                'verbose_name_plural': 'Reservas de banho',
                'ordering': ['nome', 'email', 'nome_pet', 'porte', 'data_reserva', 'turno', 'observacoes', 'petshop', 'categoria'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, 'A nota deve ser no mínimo 0.'), django.core.validators.MaxValueValidator(10, 'A nota deve ser no máximo 10.')])),
                ('comentario', models.TextField()),
                ('petshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.petshop')),
            ],
        ),
    ]
