# Generated by Django 4.2.10 on 2024-02-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='observacoes',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Observações'),
        ),
    ]
