# Generated by Django 4.2.10 on 2024-02-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pet', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=15)),
                ('data_reserva', models.DateField()),
                ('observacoes', models.CharField(max_length=2000)),
            ],
        ),
    ]
